spring:
  cloud:
    gateway:
      routes:
        - id: service-products
          uri: lb://service-products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            - ExampleCookie=Hello world API Gateway, user, ErickEstrada
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request,123456
            - AddResponseHeader=token-response,123456789
            - SetResponseHeader=Content-Type,text/plain
            - AddRequestParameter=name,Erick